Repository carpedm20/fbchat, pull requests merged in 2019-01, with the labels that each got.

#333 [Feature] Extensible attachments
  fbchat/client.py
  fbchat/graphql.py
  fbchat/models.py
  fbchat/utils.py
Labels: enhancement

#377 Fixed typos in FBchatException
  fbchat/client.py
Labels: bug

#371 Fix enums
  fbchat/graphql.py
  fbchat/models.py
  fbchat/utils.py
  requirements.txt
  setup.cfg
  setup.py
Labels: bug, help wanted

#382 Use `flit` as our build system
  .travis.yml
  MANIFEST.in
  README.rst
  dev-requirements.txt
  fbchat/__init__.py
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
Labels: enhancement

#384 Automatic GitHub Releases
  .travis.yml
Labels: enhancement

#325 [Feature] `formatMentions` method
  fbchat/models.py
Labels: enhancement
